Passarinhando/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("passarinhar.urls")),
]

passarinhar/urls.py
from django.urls import path

from passarinhar import admin

from . import views
app_name = "passarinhar"  
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("following", views.following, name="following"),    
    path("<str:username>/profile", views.profile, name="profile"),
    path("recents", views.recent_observations_view, name="recents"),
    path("locals", views.hotspots_nearby_view, name="locals"),
    path("foro", views.foro, name="foro"),
    path("mysightings", views.mysightings, name="mysightings"),
    path("allsightings", views.allsightings, name="allsightings"),
    path("favourites", views.favourites, name="favourites"),
    path("allplaces", views.allplaces, name="allplaces"),
    
    path("<str:lat>/<str:lon>/localrecents", views.localrecents, name="localrecents"),
    path("sighting/<int:sighting_id>", views.sighting, name="sighting"),

    # API Routes
    path("addNewPost", views.addNewPost, name="addNewPost"), 
    path("addNewLike", views.addNewLike, name="addNewLike"),
    path("addNewLocal", views.addNewLocal, name="addNewLocal"),
    path("addNewSpice", views.addNewSpice, name="addNewSpice"),
    path("addFavourite", views.addFavourite, name="addFavourite"),
    path("addRemoveFollowing", views.addRemoveFollowing, name='addRemoveFollowing'),    
    path("updPostContent", views.updPostContent, name='updPostContent'),   
    path("birdoftheday", views.bird_of_the_day_view, name="birdoftheday"),
]

passarinhar/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models


#class User(AbstractUser):        
#    pass


class Place(models.Model):
    place = models.CharField(max_length=100)
    lat = models.DecimalField(max_digits=10, decimal_places=7, default=0)
    lon = models.DecimalField(max_digits=10, decimal_places=7, default=0)
    subnational2Code = models.CharField(max_length=10, blank=True)
    locId = models.CharField(max_length=20, blank=True)
    latestObsDt = models.CharField(max_length=20, blank=True)
    numSpeciesAllTime = models.IntegerField(default=0)
    country= models.CharField(max_length=2, blank=True)
    region = models.CharField(max_length=100, blank=True)
    def __str__(self) -> str:
        return f"{self.place}"   
        
class WUser(AbstractUser):
    favouritesList = models.ManyToManyField(Place, blank=True, related_name="userFavourite")         
    def serialize(self):
        return {
            "user": {self.user.username},
            "favouritesList": [place.place for place in self.favouritesList.all()],
        }
    @property
    def FavouritesList_count(self):
        return self.favouritesList.count()    
   
class Follower(models.Model):
    user = models.ForeignKey(WUser, on_delete=models.CASCADE, blank=True, null=True, related_name="followerUser")
    following = models.ManyToManyField(WUser, blank=True, related_name="following")         
    #favourite_places = models.ManyToManyField(Place, blank=True, related_name="myplaces")         
    
    def serialize(self):
        return {
            "followUser": {self.user.username},
            "following": [user.username for user in self.following.all()],
            #"favourite_places": [place.place for place in self.favourite_places.all()],
        }
    @property
    def following_count(self):
        return self.following.count()
    #@property
    #def favourite_places_count(self):
    #    return self.favourite_places.count()

class Post(models.Model):
    author = models.ForeignKey(WUser, on_delete=models.CASCADE, related_name="author")    
    post_content = models.TextField(blank=True)
    likes = models.ManyToManyField(WUser, blank=True, related_name="likes")         
    timestamp = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def serialize(self):
        return {
            "id": self.id,
            "author": self.author.username,
            "postcontent": self.post_content,
            "timestamp": self.timestamp.strftime("%b %d %Y, %I:%M %p"),
            "likes":      [user.username for user in self.likes.all()],
        }
    def as_dict(self):
        return {"id": "%d" % self.id,
                "author": self.author.username,
                "postcontent": self.post_content,
                "created_at":self.timestamp.strftime('%Y-%m-%d %H:%M'),
                "updated_at":self.updated_at.strftime('%Y-%m-%d %H:%M'),
                "likes":  [user.username for user in self.likes.all()],}

    @property
    def likes_count(self):
        return self.likes.count()
    
class Comment(models.Model):
    author  = models.ForeignKey(WUser, on_delete=models.CASCADE, blank=True, null=True, related_name="commentUser")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True, related_name="commentPost")
    comment = models.TextField()
    def serialize(self):
        return f" Comment  {self.post} (by {self.author.username})"    


class Spice(models.Model):
    name = models.CharField(max_length=64, unique=True)
    spice_code = models.CharField(max_length=20, null=True, blank=True)    
    scientific_name = models.CharField(max_length=64, null=True, blank=True)
    description = models.TextField(blank=True)
    url_spice_img  = models.URLField(blank=True)
    def __str__(self) -> str:
        return f"{self.name} - {self.scientific_name}"   
    
class Sighting(models.Model):
    birder = models.ForeignKey(WUser, on_delete=models.CASCADE, related_name="owner")
    common_name = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    url_img = models.URLField(blank=True)
    spice = models.ForeignKey(Spice, on_delete=models.CASCADE, blank=True,  null=True, related_name="sighting_spice")    
    place = models.ForeignKey(Place, on_delete=models.CASCADE, blank=True,  null=True, related_name="sighting_place")    
    date_created = models.DateField(auto_now_add=True)
    def __str__(self) -> str:
        return f"{self.common_name} - {self.description}"            

passarinhar/forms.py
from django import forms

class NewPostForm(forms.Form):      
    post_content = forms.CharField(widget=forms.Textarea(attrs={'max_length':'120', "rows":"10",'class': 'form-control', 'placeholder': 'Escreve um post'}), label=False)
    

class CommentForm (forms.Form):
    newComment = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder': 'Escreve um comentário', "rows":"2"}), label=False)

class LocalsForm(forms.Form):
    lat = forms.CharField(widget=forms.HiddenInput(attrs={'id':'crnt-lat', 'max_length':'25', 'class':'form-control','label': ''}))    
    lon =forms.CharField(widget=forms.HiddenInput(attrs={'id':'crnt-lon', 'max_length':'25', 'class':'form-control','label': ''}))    
    dist = forms.FloatField(widget=forms.NumberInput(attrs={'id': 'query_limit', 'step': "1",'class': 'form-control', 'placeholder': 'Distancia'}), label="" , min_value=1, max_value=30)

class RecentsForm(forms.Form):
    lat = forms.CharField(widget=forms.HiddenInput(attrs={'id':'crnt-lat', 'max_length':'25', 'class':'form-control','label': ''}))    
    lon =forms.CharField(widget=forms.HiddenInput(attrs={'id':'crnt-lon', 'max_length':'25', 'class':'form-control','label': ''}))    
    quantos = forms.FloatField(widget=forms.NumberInput(attrs={'id': 'query_limit', 'step': "1",'class': 'form-control', 'placeholder': 'Quantos'}), label="" , min_value=1, max_value=30)

passarinhar/views.py
# Create your views here.
from dbm import error
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from .models import WUser, Post, Follower, Sighting, Place, Spice
from django.core.paginator import Paginator
from django.conf import settings
#from django.contrib.gis.geoip2 import GeoIP2
from .forms import CommentForm, RecentsForm, LocalsForm
import requests
import folium

def fetch_hotspots_nearby(lat, lon, dist = 25):
    api_key = settings.EBIRD_API_KEY
    
    url = f"https://api.ebird.org/v2/ref/hotspot/geo?lat={lat}&lng={lon}&fmt=json&dist={dist}"
    print(url)
    payload={}
    headers = {
      'X-eBirdApiToken': api_key
    }    
    response = requests.request("GET", url, headers=headers, data=payload)    
    # print(api_key, response.text)    
    data = response.json()
    return {
        'data': data 
    }

def fetch_recent_observations_in_a_region(lat, lon, howmany = 1):
    api_key = settings.EBIRD_API_KEY
    locale = "pt-br"
    region = "BR-RJ-049"
    maxResults = howmany
    if lat == '':
        print('fetch_recent_observations_in_a_region')
        url = f"https://api.ebird.org/v2/data/obs/{region}/recent?sppLocale={locale}&maxResults={str(maxResults)}"
    else:
        print('fetch_recent_observations_in_a_LoC')
        url = f"https://api.ebird.org/v2/data/obs/geo/recent?lat={lat}&lng={lon}&sppLocale={locale}&maxResults={str(maxResults)}&detail=full"       
        
    print(url)
    payload={}
    headers = {
      'X-eBirdApiToken': api_key
    }    
    response = requests.request("GET", url, headers=headers, data=payload)    
    # print(api_key, response.text)
    
    data = response.json()
    return {
        'data': data 
    }

def allplaces(request):    
    error = None
    allplaces = Place.objects.all()
    allplaces = allplaces.order_by("-pk").all()   
    p = Paginator(allplaces, 30)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    hotspots_nearby_data = page_obj    
    if hotspots_nearby_data:
        home_map = show_on_map(hotspots_nearby_data[0].lat, hotspots_nearby_data[0].lon, "allplaces", hotspots_nearby_data)
        map_html = home_map._repr_html_()    
    else:
        error = 'Nenhum local registrado!'
        map_html = None
    
    return render(request, "passarinhar/places.html", {
        'title':"Locais de Avistamento Registrados",
        "page_name": 'allplaces',        
        'page_obj':page_obj,
        "hotspots_nearby_data": hotspots_nearby_data,
        "nearby_map":map_html,
        "error": error
        })
            
def addFavourite(request):
    
    data = json.loads(request.body)    
    place_id = data.get('place_id','')
    fav = None
    try:
        place = Place.objects.get(pk=place_id)
        currentUser = WUser.objects.get(pk=request.user.id)
        if place in currentUser.favouritesList.all():    
            fav = False
            currentUser.favouritesList.remove(place) 
        else:
            fav = True
            currentUser.favouritesList.add(place)                
        currentUser.save()

    except WUser.DoesNotExist:
        raise Http404("Place not found.")

    
    return JsonResponse({"userFav": fav})        
          
def favourites(request):    
    error = None
    
    # Filter places returned based on favourites:
    user = WUser.objects.filter(id = request.user.id)    
    fav_places = Place.objects.filter(id__in=user.values_list("favouritesList", flat=True))  
                      
    # Return all user favourite places in reverse chronologial order
    fav_places = fav_places.order_by("-pk").all()
    
    p = Paginator(fav_places, 30)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    
    hotspots_nearby_data = page_obj    
    if hotspots_nearby_data:
        home_map = show_on_map(hotspots_nearby_data[0].lat, hotspots_nearby_data[0].lon, "favourite", hotspots_nearby_data)
        map_html = home_map._repr_html_()    
    else:
        map_html = None
        error = 'Nenhum local registrado como favorito!'
    return render(request, "passarinhar/places.html", {
        'title':"Locais de Avistamento Favoritos",
        "page_name": 'favs',        
        'page_obj':page_obj,
        "hotspots_nearby_data": hotspots_nearby_data,
        "nearby_map":map_html,
        "error": error   
        })                      
    
def hotspots_nearby_view(request):
    hotspots_nearby_data = None
    error = None
    home_map = None
    map_html = None
    if request.method == 'POST':
        form = LocalsForm(request.POST)
        if form.is_valid():
            latitude = request.POST["lat"]
            longitude = request.POST["lon"]
            dist = request.POST['dist']        
            hotspots_nearby_data = fetch_hotspots_nearby(
                latitude,longitude,dist)                        
            
            if len(hotspots_nearby_data['data']) == 0 :
                error = 'Nenhum local encontrado!' 
            else:
                hotspots_nearby_data = hotspots_nearby_data['data']
                home_map = show_on_map(latitude, longitude, "hotspot", hotspots_nearby_data)
                map_html = home_map._repr_html_()                      
        else:  
            pass
    else:
        form = LocalsForm(initial={"dist":15})      
    return render(request, "passarinhar/locais.html", {
            "title":'Locais de avistamento na região',
            "form": form,
            "error":error,
            "hotspots_nearby_data": hotspots_nearby_data,
            "nearby_map":map_html
        })

def show_on_map(latitude, longitude, type, hotspots_nearby):
    
    if type != "hotspot":
        locName_list = [item.place for item in hotspots_nearby] 
        lng_list = [item.lon for item in hotspots_nearby]
        lat_list = [item.lat for item in hotspots_nearby]
    else:
        lng_list = [item['lng'] for item in hotspots_nearby]
        lat_list = [item['lat'] for item in hotspots_nearby]
        locName_list = [item['locName'] for item in hotspots_nearby] 
    
    home_map = folium.Map(location=[latitude, longitude], zoom_start=12)
    
    # instantiate a feature group for the nearby stations in the dataframe
    nearby_places = folium.map.FeatureGroup()

    # loop through the 20 stations nearby and add each to the feature group
    for lat, lng, in zip(lat_list, lng_list):
        nearby_places.add_child(
            folium.features.CircleMarker(
                [lat, lng],
                radius=5, # define how big you want the circle markers to be
                color='yellow',
                fill=True,
                fill_color='blue',
                fill_opacity=0.6
            )
        )
    # add pop-up text to each marker on the map
    folium.Marker([latitude, longitude], popup="Sua localização").add_to(home_map)
    for lat, lng, label in zip(lat_list, lng_list, locName_list):
        folium.Marker([lat, lng], popup=label).add_to(home_map)
    # add places to map
    home_map.add_child(nearby_places)
    return home_map

def bird_of_the_day_view(request):
    try:         
        if request.headers.get('content-type') == 'application/json':      
            data = json.loads(request.body)    
            latitude = data.get('lat','')
            longitude = data.get('lon','')    
            howmany = 1  
            recent_observations_data = fetch_recent_observations_in_a_region(
                latitude,
                longitude,
                howmany
            ) 
            if len(recent_observations_data['data']) > 0 :            
                return JsonResponse({
                    'data': recent_observations_data['data']})        
        else:
            return JsonResponse({'error': 'Nenhum passaro encontrado!'})
                       
    except Exception as e:
       return JsonResponse({'error': str(e)})

def addNewSpice(request):
    try:
        if request.method == 'POST':
            data = json.loads(request.body)    
            name = data.get('name','')
            spice_code = data.get('spice_code','')
            scientific_name = data.get('scientific_name','')
            description = data.get('description','')
            url_spice_img = data.get('url_spice_img','')
            current = Spice.objects.filter(name=name)
            if current:
                message = 'Passarinho já cadastrado.'                                
            else:
                new_spice = Spice(
                spice_code=spice_code,
                name=name,                
                scientific_name=scientific_name,
                description=description,
                url_spice_img=url_spice_img
                )
                new_spice.save()
                message = f'Passarinho {name} cadastrado com sucesso.'                        
            return JsonResponse({'message': message})
    except Exception as e:
       return JsonResponse({'message': str(e)})

def addNewLocal(request):
    if request.method == 'POST':
        data = json.loads(request.body)    
        lat = data.get('lat','0')
        lon = data.get('lon','0')
        current = Place.objects.filter(lat=data.get('lat',''), lon=data.get('lon') )
        if current:
            message = 'Local já cadastrado.'                                
        else:
            locId = data.get('locId','')
            place = data.get('place','')
            subnational2Code = data.get('subnational2Code','')
            latestObsDt = data.get('latestObsDt','')
            numSpeciesAllTime = data.get('numSpeciesAllTime','')
               
            country= subnational2Code.split('-')[0]
            region = subnational2Code.split('-')[1]
            new_local = Place(

passarinhar/templates/passarinhar/foro.html
{% extends "passarinhar/layout.html" %}
{% load static %}

{% block body %}
<h2 id="page-title">{{ title }}</h2>

<div id='error-msg' class='alert alert-warning' style="display:none;" ;></div>

<script>
    var update_url = "{% url 'passarinhar:updPostContent' %}";
    var unfollow_url = "{% url 'passarinhar:addRemoveFollowing' %}";
    var like_url = "{% url 'passarinhar:addNewLike' %}";
</script>
{% if page_name == 'foro' and user.is_authenticated %}
<div id="newpost-view" class="p-1 my-1 bg-white text-dark border border-secondary">
    <h3>Novo Post</h3>
    <form action="{% url 'passarinhar:addNewPost' %}" method="post" id="newpost-form">
        {% csrf_token %}
        <textarea class="form-control" id="newpost-content" name="postcontent" placeholder="New Post"></textarea>
        <input type="submit" class="btn btn-primary" />
    </form>
</div>
{% endif %}

{% if page_name == 'profile' %}
<div id="profile-view" style="display: block;">
    <ul>
        {% if user.is_authenticated and user == profile_obj %}
        <li><a id="my-sights" href="{% url 'passarinhar:mysightings' %}">Meus avistamentos</a></li>
        <li><a id="my-places" href="{% url 'passarinhar:favourites' %}">Meus locais favoritos</a></li>
        {% endif %}
        <li id="prf-followers">Seguidores: {{ followers }}</li>
        <li id="prf-following">Seguindo a: {{ following }}</li>
    </ul>
    {% if user.is_authenticated and user != profile_obj %}
    <script src="{% static 'passarinhar/profile.js' %}"></script>
    {% csrf_token %}
    <button id="follow-btn" class="button" data-profile="{{ title }}" value="{{follow_label}}">{{follow_label}}</button>
    {% endif %}
</div>
{% endif %}
<div id="posts-view">
    {% for post in page_obj %}
    <div class="p-1 my-1 bg-white text-dark border border-secondary">
        <div><a href="{% url 'passarinhar:profile' post.author.username %}">{{ post.author }}</a></div>

        <div id="{{post.id}}">
            {% if user.is_authenticated and user == post.author %}
            <div id="edit-div{{post.id}}">
                <button id="edit-btn{{post.id}}" class="button edit" data-id="{{post.id}}">Editar</button>
            </div>
            {% endif %}
            <div>{{post.post_content|linebreaksbr}}</div>
        </div>

        <div class="editdiv" id="edit-sec{{post.id}}" style='display:none' data-id="{{post.id}}">
            <form id="updt-form{{post.id}}" data-id="{{ post.id }}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <textarea name="content{{post.id}}" class="form-control"
                        id="content{{post.id}}">{{post.post_content}}</textarea>
                </div>
                <input type="submit" id="updt-btn{{post.id}}" class="btn btn-primary" data-id="{{ post.id }}" />
                <input type="reset" value='Discard' id="close-btn{{post.id}}" class="btn btn-secondary"
                    data-id="{{ post.id }}" />
            </form>
        </div>

        <div id="timestamp">{{ post.timestamp }} <i>(Atualizado em {{ post.updated_at }})</i></div>

        <div id="like">
            {% if user != post.author %}
            {% csrf_token %}
            <span id="like-btn{{post.id}}" class="like-button" data-id="{{post.id}}"><i id="like-icon{{post.id}}"
                    style="color:grey" class="fa fa-heart"></i></span>
            {% else %}
            <i id="like-icon{{post.id}}" style="color:grey" class="fa fa-heart"></i>
            {% endif %}

            <span id="like_count{{post.id}}" data-id="{{post.id}}">{{ post.likes.count }}</span>
        </div>

        {% if user.is_authenticated and user != post.author %}
        <div id="comments">
            <form id="comment-form" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <textarea class="form-control" id="comment-content" name="commentcontent"
                        placeholder="Comentário"></textarea>
                </div>
                <div class="form-group">
                    <button id="comment-btn" type="submit" class="btn btn-primary">Comentar</button>
                </div>
            </form>
        </div>
        {% endif %}
    </div>
    {% empty %}
    <div>*** Nenhum post***</div>
    {% endfor %}
</div>
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1"><span aria-hidden="true">&laquo; </span>
                Primeira</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                {{page_obj.previous_page_number }}</a></li>
        {% endif %}
        <li class="page-item  active" aria-current="page"><a class="page-link" href="?page={{ page_obj.number }}">
                {{page_obj.number}}</a></li>
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">
                {{page_obj.next_page_number}}</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                Ultima<span aria-hidden="true"> &raquo;</span></a></li>
        {% endif %}
    </ul>
</nav>

{% block script %}
{% if user.is_authenticated %}
<script src="{% static 'passarinhar/components.js' %}"></script>
{% endif %}
{% endblock %}
{% endblock %}

passarinhar/templates/passarinhar/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Passarinhar{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'passarinhar/styles.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="#">
</head>

<body>
    <nav class="container navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'passarinhar:index' %}">Passarinhar</a>
        <div>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" id="ebird-sights"
                        href="{% url 'passarinhar:recents'%}">Avistamentos - eBird</a>
                </li>
                <li class="nav-item"><a class="nav-link" id="ebird-places" href="{% url 'passarinhar:locals'%}">Locais -
                        eBird</a>
                </li>
                <li class="nav-item"><a class="nav-link" id="allpost" href="{% url 'passarinhar:foro' %}">Foro</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" id="all-sights"
                        href="{% url 'passarinhar:allsightings' %}">Avistamentos registrados</a>
                </li>
                <li class="nav-item"><a class="nav-link" id="all-places" href="{% url 'passarinhar:allplaces' %}">Locais
                        registrados</a>
                </li>
                <li class="nav-item"><a class="nav-link" id="user"
                        href="{% url 'passarinhar:profile' user.username %}"><strong>{{user.username }}</strong></a>
                </li>
                <li class="nav-item"><a class="nav-link" id="following"
                        href="{% url 'passarinhar:following' %}">Seguindo</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'passarinhar:logout' %}">Sair</a>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'passarinhar:login' %}">Entrar</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'passarinhar:register' %}">Cadastrar</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container body">
        {% block body %}
        {% endblock %}
    </div>
</body>

</html>

passarinhar/templates/passarinhar/login.html
{% extends "passarinhar/layout.html" %}

{% block body %}

<h2>Login</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'passarinhar:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Login">
</form>

Não tem uma conta? <a href="{% url 'passarinhar:register' %}">Registre-se aqui.</a>

{% endblock %}

passarinhar/templates/passarinhar/register.html
{% extends "passarinhar/layout.html" %}

{% block body %}

<h2>Register</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'passarinhar:register' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Email Address">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Register">
</form>

Já tem uma conta? <a href="{% url 'passarinhar:login' %}">Faça login aqui.</a>

{% endblock %}

passarinhar/templates/passarinhar/sighting.html
{% extends "passarinhar/layout.html" %}
{% load l10n %}
{% block body %}
    {% if message %}
        {% if updated %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
        {% endif %}
    {% endif %}
    <div class="p-1 my-1 bg-white text-dark border border-secondary">
        <h2>{{ sighting.title }}</h2>
        <img src="{{sighting.url_img}}" alt="{{sighting.title}}" title="{{sighting.title}}" class="img-responsive" />      
        <p>{{ sighting.description }}</p>
        <hr>        
        <ul>
        <li>Especie: {{ sighting.spice }}</li>
        <li>Usuário: {{ sighting.birder }}</li>
        <li>Local: {{ sighting.place }}</li>
        <li>Data: {{ sighting.date_created }}</li>
        </ul> 
        <div class="container">                                             
            <a href="{% url 'passarinhar:allsightings' %}">Voltar para a lista de avistamentos</a>                    
        </div>
    </div>  
{% endblock %}